In [18]:
import numpy as np;
np.set_printoptions(suppress=True) #不使用科学计数法
#创建矩阵
a=np.array([[1,2],[3,4]]);
print(a)

[[1 2]
 [3 4]]


In [19]:
# 创建一个4行3列的空数组
print(np.empty((4,3)))
#创建一个 4*4矩阵 默认值都是0
print(np.zeros((4,4)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
#创建一个方形矩阵 对角线是1  其他值都是0
"""
对角线，几何学名词，定义为连接多边形任意两个不相邻顶点的线段，或者连接多面体任意两个不在同一面上的顶点的线段
另外在代数学中，n阶行列式，从左上至右下的数归为主对角线，从左下至右上的数归为副对角线
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
"""
po=np.eye(4)
print(po);

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# 创建一个 3*3矩阵 默认值都是1
print(np.ones((3,3)))

In [25]:
#创建一个5*5矩阵 初始值全部是5
po=np.full((5,5),5)
print(po);

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [27]:
# 产生一个等差数列 1、arange(start，stop，step)  step是差值,步长
bb=np.arange(-10,10,1) #等价np.array([n for n in range(-10,10,1)]);#等价
print(bb)
print(np.array([n for n in range(-10,10,1)]))

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]


In [22]:
#创建等差数列 linspace(start,stop,num) 这里的num是个数，表示在start和stop之间创建num个值
matrix_linspace = np.linspace(2,20,10)
print(matrix_linspace);


[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [23]:
#logspace创建等比数列 logspace(start,stop,num) 同linspace，这里的num指的是个数，指在start和stop之间创建num个数
matrix_logspace = np.logspace(2,20,10)
print(matrix_logspace)

[1.e+02 1.e+04 1.e+06 1.e+08 1.e+10 1.e+12 1.e+14 1.e+16 1.e+18 1.e+20]


In [28]:
'''
沿着轴线将数据设置成索引值
[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]] 水平
 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]] 垂直
'''
po=np.indices((3,4));
print(po);


[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]
