In [4]:
import numpy as np
#默认按照行排序
p=np.array([[-1,8],
            [4,-2]
            ]);
# 默认是在横轴上排序，也就是-1和8排序，4和-2排序
print(np.sort(p))
# 指定为纵轴上排序也就是是-1和4排序，8和-2排序
print(np.sort(p,axis=0))


[[-1  8]
 [-2  4]]
[[-1 -2]
 [ 4  8]]


In [5]:
#自定义对象数据类型 参考http://www.runoob.com/numpy/numpy-dtype.html 按照字段排序
mtype=np.dtype([('name','S'),('age',int)])
p=np.array([('zs',20),('ww',60),('zl',30)],dtype=mtype)
print(np.sort(p,order='age'))



[(b'', 20) (b'', 30) (b'', 60)]


In [6]:
p=np.array([3,1,2])
#argsort() 函数返回的是数组值从小到大的索引值。
print(np.argsort(p))

[1 2 0]


In [7]:
#逆序
print(np.sort(p)[::-1])


[3 2 1]
