In [65]:
import numpy as np
# 創建兩個二維矩陣，一般二维矩阵，行表示一个样本，列表示特征
# 创建个1-10步长为1的等比数列，修改为3*3的矩阵
'''
[[1 2 3]
 [4 5 6]
 [7 8 9]]
'''
p=np.arange(1,10).reshape((3,3));
p1=np.array([   [-1,4,6],
                [-2,8,11],
                [8,3,1]
            ]);
print(p);
print(p1);

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1  4  6]
 [-2  8 11]
 [ 8  3  1]]


In [66]:
'''
stack:英文解释 洗牌
在纵轴上垂直合并
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [-1  4  6]
 [-2  8 11]
 [ 8  3  1]]
'''
print(np.vstack((p,p1))) #垂直合并
print(np.concatenate((p,p1),axis=0));#合并矩阵 默认在0号维度上（参考learn_algorithm/axis维度理解.png）拓展也就是已有元素垂直方向上

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [-1  4  6]
 [-2  8 11]
 [ 8  3  1]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [-1  4  6]
 [-2  8 11]
 [ 8  3  1]]


In [67]:
'''
在已有元素水平方向（右边）叠加元素
[[ 1  2  3 -1  4  6]
 [ 4  5  6 -2  8 11]
 [ 7  8  9  8  3  1]]
'''

print(np.hstack((p,p1)))
print(np.concatenate((p,p1),axis=1));

[[ 1  2  3 -1  4  6]
 [ 4  5  6 -2  8 11]
 [ 7  8  9  8  3  1]]
[[ 1  2  3 -1  4  6]
 [ 4  5  6 -2  8 11]
 [ 7  8  9  8  3  1]]


In [68]:
'''
默认所有元素不管多少维度都合并为一个1维数组,两个合并数组可以是不同维度
[1 2 3 7 8 9 4 5 6]
'''
print(np.append([[1,2,3],[7,8,9]],[[4,5,6]]))
print(np.append([[1,2,3],[7,8,9]],[4,5,6]))
#如果需要同concatenate在坐标轴上连接，对应轴的长度必须是一致的
print(np.append([[1,2,3],[7,8,9]],[[4,5,6]],axis=0))
#以下在纵轴上的长度是3个右侧的是2个就会报错
#print(np.append([[1,2,3],[7,8,9]],[[4,5]],axis=0))

[1 2 3 7 8 9 4 5 6]
[1 2 3 7 8 9 4 5 6]
[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [69]:
'''
深度组合：沿着纵轴方向组合
原始数组

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1  4  6]
 [-2  8 11]
 [ 8  3  1]] 
 取出合并的两个数组的一行 沿着纵轴组合 
结果：
[[[ 1 -1]
  [ 2  4]
  [ 3  6]]
 [[ 4 -2]
  [ 5  8]
  [ 6 11]]
 [[ 7  8]
  [ 8  3]
  [ 9  1]]]  
'''
print(np.dstack((p,p1)))

[[[ 1 -1]
  [ 2  4]
  [ 3  6]]

 [[ 4 -2]
  [ 5  8]
  [ 6 11]]

 [[ 7  8]
  [ 8  3]
  [ 9  1]]]


In [78]:
#stack的本质作用是在干什么？stack为堆叠的意思，它的本质是在给数组升维
#axios=0表示在一维上堆叠，axis表示在二维上堆叠，参考：https://blog.csdn.net/qq_37006426/article/details/116238818
np.stack(([1,2,4],[3,6,8]),axis=0)


array([[1, 2, 4],
       [3, 6, 8]])