In [113]:
import numpy as np
p=np.array([[-1,4],
            [-2,8]
            ]);
p1=np.array([[4,6],
            [3,1]
            ]);
#矩阵乘法是将各个位置的值相乘,参考：https://www.cnblogs.com/hun2014/articles/14676974.html
print(p*p1);
print(np.multiply(p,p1)) #等价于上面

[[-4 24]
 [-6  8]]
[[-4 24]
 [-6  8]]


In [114]:
# 矩阵叉乘又叫矩阵乘，只有前者的列数等于后者的行数，才能进行叉乘运算。
#参考learn_algorithm/矩阵乘法.png
print(p.dot(p1))
print(np.matmul(p,p1))#两个数组的矩阵积，和上面效果相同

[[ 8 -2]
 [16 -4]]
[[ 8 -2]
 [16 -4]]


In [115]:
#概念参考：https://www.shuxuele.com/algebra/vectors-dot-product.html
print(np.vdot([1,2],[3,4])) #两个【向量】的点积  1*2+2*3=8


11


In [116]:
#行列式：https://www.shuxuele.com/algebra/matrix-determinant.html
print(np.linalg.det(p))


0.0


In [117]:
#矩阵的内积 参考：https://blog.csdn.net/zhinanpolang/article/details/104957513
print(np.inner(p,p1))

[[20  1]
 [40  2]]


In [118]:
#求逆矩阵,概念参考：learn_algorithm/逆矩阵.png
print(np.linalg.inv([[1,2],[3,5]]))

[[-5.  2.]
 [ 3. -1.]]


In [119]:
#矩阵的转置
p=np.array([[-1,4,5],
            [-2,8,6]
            ]);
#将第一行转换成第一列 其他行转换其他列，第i行转换为第i列
#行列个数发生了变化
print(np.transpose(p))
#等价于
print(p.T)


[[-1 -2]
 [ 4  8]
 [ 5  6]]
[[-1 -2]
 [ 4  8]
 [ 5  6]]


In [120]:
#不是一维数组会转换为[-1,4,5,-2,8,6]
#求最大值和最小值
print(np.max(p),np.min(p))
#求最大|小值的坐标
print(np.argmax(p),np.argmin(p))
#获取当前维度的最大值，制定了维度不会转换为一维数组 axis是横轴就是每一行的最大值
print(np.max(p,axis=1))

8 -2
4 3
[5 8]


In [121]:
#求平均值
p1=np.array([[4,6],
            [3,1]
            ]);
print(np.mean(p1))  #4+6+3+1/4=3.5 也可以设置水平和垂直
print(np.mean(p1,axis=0)) #[3.5,3.5] 垂直
print(np.mean(p1,axis=1)) #[5,2] 水平


3.5
[3.5 3.5]
[5. 2.]


In [122]:
#求方差
arr = np.array([1, 2, 3, 100, 55])
# var 方差即各项-均值的平方求和后再除以N ，表示数据离平均数据的距离的平均值，表示数据的离散程度
# 方差越小表示所有数据离平均值越小，越聚集，否则越离散。
print(np.var(arr))
print(np.sum(np.abs(arr - np.mean(arr)) ** 2) / len(arr))  # 等价代码
print(np.mean(abs(arr - arr.mean()) ** 2))  # 等价代码

1570.96
1570.96
1570.96


In [123]:
# std：表示标准差，是var的平方根。
print(np.std(arr))
print(np.sqrt(np.var(arr)));

39.635337768208814
39.635337768208814


In [124]:
# cov：协方差 ,用来表示两个点的运行轨迹是否一致
# 协方差理解：learn_algorithm/如何通俗易懂地解释「协方差」与「相关系数」的概念.png
# 协方差本来是用来计算多个特征的趋近程度，如果没有第二个特征就是一维数组，就等于方差,协方差是除以n-1
print(np.cov(arr));
print(np.sum(np.abs(arr - np.mean(arr)) ** 2) / (len(arr) - 1))  # 等价代码

# 协方差主要是多个特征
pa=np.array([
     [1,2] ,
     [3,6] ,
     [4,2] ,
     [5,2] 
   ])
'''
 x应该是个二维矩阵表示
 [
     [1] ,
     [3] ,
     [4] ,
     [5] 
   ]
'''
x=np.array([pa[:,0]]).reshape((4,1))
'''
 y应该是个二维矩阵表示
 [
     [2] ,
     [6] ,
     [2] ,
     [2] 
   ]
'''
y=np.array([pa[:,1]]).reshape((4,1))
print("分别获取X和Y:",x,y)
x_mean=np.mean(x)
y_mean=np.mean(y)
print("x和y特征的均值",x_mean,y_mean)
'''
这里只是求第一个特征x（第一列）和第二个特征(第二列)的方差cov(x,y)，
，实际还有cov(x,x),cov(y,x),cov(y,y)
x-x_mean转置T就变成了
 [
     [1-xmean,3-xmean,4-xmean,5-xmean] 
 ]
y-ymean是
 [
     [2-ymean] ,
     [6-ymean] ,
     [2-ymean] ,
     [2-ymean] 
 ]
(x-x_mean).T.dot(y-y_mean)就变成了矩阵乘法了

（1-xmean）*（2-ymean）+（3-xmean）*（6-ymean）+（4-xmean）*（2-ymean）+（5-xmean）*（2-ymean）
然后除以n-1就是协方差了cov(x,y)
'''
print("cov(x,y)=",np.sum((x-x_mean).T.dot(y-y_mean))/(len(pa)-1))

#数学表示横表示列，竖表示行，默认行横表示特征
'''
[[1 3 4 5]
 [2 6 2 2]]
'''
print(pa.T)
print("conv",np.cov(pa.T))
# 使用rowvar=False，表示列是变量是特征
print("conv",np.cov(pa,rowvar=False))

1963.6999999999998
1963.7
分别获取X和Y: [[1]
 [3]
 [4]
 [5]] [[2]
 [6]
 [2]
 [2]]
x和y特征的均值 3.25 3.0
cov(x,y)= -0.3333333333333333
[[1 3 4 5]
 [2 6 2 2]]
conv [[ 2.91666667 -0.33333333]
 [-0.33333333  4.        ]]
conv [[ 2.91666667 -0.33333333]
 [-0.33333333  4.        ]]
