In [14]:
import numpy as np;
theta=np.array([[0.5,0.5]])
theta0=1
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x)
print(theta.T)
print(np.dot(x,theta.T))




[[1 2]
 [3 4]
 [5 6]]
[[0.5]
 [0.5]]
[[1.5]
 [3.5]
 [5.5]]
