In [124]:
import numpy as np;
import matplotlib.pyplot as plot;
# 数学中行是表示特征
X=np.array([
    [1,1,2,4,2],
    [1,3,3,4,4]
])
# 转置为列为特征
X=X.T
print(X)

[[1 1]
 [1 3]
 [2 3]
 [4 4]
 [2 4]]


In [125]:
#均值归零
x_demean=np.mean(X,axis=0)
X_Zero=X-x_demean
print("均值：",x_demean)
print(X_Zero)

均值： [2. 3.]
[[-1. -2.]
 [-1.  0.]
 [ 0.  0.]
 [ 2.  1.]
 [ 0.  1.]]


In [126]:
#计算对应的协方差矩阵,手撕或者使用np.conv
con=X_Zero.T.dot(X_Zero)/(len(X_Zero)-1)
con1=np.cov(X_Zero,rowvar=False)
print("协方差：",con,"\n",con1)

协方差： [[1.5 1. ]
 [1.  1.5]] 
 [[1.5 1. ]
 [1.  1.5]]


In [127]:
#依据协方差矩阵计算特征值和特征向量,转换参考 矩阵计算.ipynb
f_value,f_vector=np.linalg.eig(con)
eig=[(f_value[i],f_vector[:,i])for i in range(len(f_value))]
print("特征值-特征向量",eig)

特征值-特征向量 [(2.5, array([0.70710678, 0.70710678])), (0.5, array([-0.70710678,  0.70710678]))]


In [128]:
#获取最大值的索引
max_f_value_index=np.argsort(f_value)[::-1][0]
print(np.array([eig[max_f_value_index][1]]).dot(X_Zero.T))
print(X_Zero.dot(np.array([eig[max_f_value_index][1]]).T))


[[-2.12132034 -0.70710678  0.          2.12132034  0.70710678]]
[[-2.12132034]
 [-0.70710678]
 [ 0.        ]
 [ 2.12132034]
 [ 0.70710678]]
